"""Markdown daily report generator.

Uses an injected AIAnalyzer and the daily report prompt configuration to
turn AnalysisResult objects into a Markdown report.
"""

from __future__ import annotations

import json
from dataclasses import asdict
from datetime import date, datetime
from pathlib import Path
from typing import Any, Sequence
from uuid import uuid4

import yaml

from analyzers.analyzer import AIAnalyzer
from analyzers.schemas import AnalysisResult
from analyzers.trend_analyzer import TrendAnalysis
from reports.data_aggregator import ReportItem
from utils.logger import logger


PROJECT_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_PROMPT_PATH = PROJECT_ROOT / "prompts" / "daily_report.yaml"
DEFAULT_OUTPUT_DIR = PROJECT_ROOT / "reports" / "output"


class MarkdownReportError(Exception):
    """Raised when report generation or saving fails."""


class MarkdownReportGenerator:
    """Generate a Markdown daily report through an AIAnalyzer."""

    def __init__(
        self,
        analyzer: AIAnalyzer,
        prompt_config: dict[str, Any] | Path = DEFAULT_PROMPT_PATH,
    ) -> None:
        self._analyzer = analyzer
        self._prompt_config = self._load_prompt_config(prompt_config)

    def generate(
        self,
        results: Sequence[AnalysisResult | ReportItem],
        trend_analysis: TrendAnalysis | None = None,
    ) -> str:
        """Serialize results, prompt the AI, and return Markdown.

        Args:
            results: Analyzed articles to include in the report.

        Returns:
            Markdown text generated by the AI.

        Raises:
            MarkdownReportError: If generation fails or output is empty.
        """

        try:
            payload = [
                self._to_payload(result) for result in results
            ]
            trend_payload: dict[str, Any] = {}
            if trend_analysis is not None:
                trend_payload = trend_analysis.to_dict()
            data_payload = json.dumps(
                {"articles": payload, "trend_analysis": trend_payload},
                ensure_ascii=False,
                indent=2,
            )
            prompt = self._build_prompt(data_payload)
            analysis = self._analyzer.analyze(prompt)
            markdown = analysis.summary.strip()
        except Exception as exc:
            logger.error("Failed to generate daily report: {}", exc)
            raise MarkdownReportError(
                f"Failed to generate daily report: {exc}"
            ) from exc

        if not markdown:
            raise MarkdownReportError("AI returned an empty report")
        return markdown

    @staticmethod
    def _to_payload(item: AnalysisResult | ReportItem) -> dict[str, Any]:
        if isinstance(item, ReportItem):
            excerpt = item.article_summary or item.article_content[:500]
            return {
                "importance": item.importance,
                "category": item.category,
                "tags": item.tags,
                "summary": item.summary,
                "impact": item.impact,
                "action": item.action,
                "article_title": item.article_title,
                "article_link": item.article_link,
                "article_published_at": item.article_published_at,
                "original_excerpt": excerpt,
            }
        return asdict(item)

    def save_report(
        self,
        content: str,
        report_date: date | None = None,
        output_dir: Path | None = None,
    ) -> Path:
        """Save a report using a date-based filename.

        Args:
            content: Markdown report text.
            report_date: Report date used in the filename.
            output_dir: Output directory override for testing.

        Returns:
            The path of the saved report.
        """

        target_date = report_date or date.today()
        directory = output_dir or DEFAULT_OUTPUT_DIR
        try:
            directory.mkdir(parents=True, exist_ok=True)
            timestamp = datetime.now().strftime("%Y%m%d-%H%M%S-%f")
            unique = uuid4().hex[:8]
            path = (
                directory
                / (
                    f"{target_date.isoformat()}-{timestamp}-{unique}"
                    "-ai-tech-radar.md"
                )
            )
            path.write_text(content, encoding="utf-8")
        except OSError as exc:
            logger.error("Failed to save daily report: {}", exc)
            raise MarkdownReportError(
                f"Failed to save daily report: {exc}"
            ) from exc
        return path

    def _build_prompt(self, data_payload: str) -> str:
        system_prompt = str(self._prompt_config.get("system_prompt", ""))
        instructions = self._prompt_config.get("instructions", [])
        output_format = str(self._prompt_config.get("output_format", ""))
        rules = self._prompt_config.get("rules", {})
        instruction_lines = "\n".join(f"- {item}" for item in instructions)
        rules_text = yaml.safe_dump(
            rules, allow_unicode=True, sort_keys=False
        ).strip()
        return "\n\n".join(
            [
                system_prompt,
                f"Instructions:\n{instruction_lines}",
                f"Output format:\n{output_format}",
                f"Rules:\n{rules_text}",
                f"Data:\n{data_payload}",
            ]
        )

    @staticmethod
    def _load_prompt_config(
        prompt_config: dict[str, Any] | Path,
    ) -> dict[str, Any]:
        if isinstance(prompt_config, Path):
            if not prompt_config.is_file():
                raise MarkdownReportError(
                    f"Prompt file not found: {prompt_config}"
                )
            try:
                with prompt_config.open("r", encoding="utf-8") as handle:
                    data = yaml.safe_load(handle)
            except yaml.YAMLError as exc:
                raise MarkdownReportError(
                    f"Invalid prompt YAML: {exc}"
                ) from exc
            if not isinstance(data, dict):
                raise MarkdownReportError(
                    "Prompt config must be a mapping"
                )
            return data
        return prompt_config
